// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADzTUdCfG0wKDQeRNs7Lp_TmPM5iw56TA',
    appId: '1:875483519236:web:08ad199b9d75b479845851',
    messagingSenderId: '875483519236',
    projectId: 'samaufr-965c4',
    authDomain: 'samaufr-965c4.firebaseapp.com',
    storageBucket: 'samaufr-965c4.firebasestorage.app',
    measurementId: 'G-57MHKX8RKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv0oCqGakseWmJzoUGqP4fR3iKGfeMVr4',
    appId: '1:875483519236:android:e77203d4fbcfc4c8845851',
    messagingSenderId: '875483519236',
    projectId: 'samaufr-965c4',
    storageBucket: 'samaufr-965c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPULi86j3YeZMt3yU-28fs0LcK9Q1-dxU',
    appId: '1:875483519236:ios:fd73a70b43eda15d845851',
    messagingSenderId: '875483519236',
    projectId: 'samaufr-965c4',
    storageBucket: 'samaufr-965c4.firebasestorage.app',
    iosBundleId: 'sn.ugb.eTontee.samaUfr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPULi86j3YeZMt3yU-28fs0LcK9Q1-dxU',
    appId: '1:875483519236:ios:fd73a70b43eda15d845851',
    messagingSenderId: '875483519236',
    projectId: 'samaufr-965c4',
    storageBucket: 'samaufr-965c4.firebasestorage.app',
    iosBundleId: 'sn.ugb.eTontee.samaUfr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADzTUdCfG0wKDQeRNs7Lp_TmPM5iw56TA',
    appId: '1:875483519236:web:c2756b134b924b45845851',
    messagingSenderId: '875483519236',
    projectId: 'samaufr-965c4',
    authDomain: 'samaufr-965c4.firebaseapp.com',
    storageBucket: 'samaufr-965c4.firebasestorage.app',
    measurementId: 'G-17CZP64F3W',
  );
}
